{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.secretStore.create -}}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecrets.secretStoreRef.name }}
  labels:
    {{- include "popper.labels" . | nindent 4 }}
spec:
  provider:
    {{- if eq (.Values.externalSecrets.provider | default "vault") "aws" }}
    aws:
      service: {{ .Values.externalSecrets.aws.service | default "SecretsManager" }}
      region: {{ .Values.externalSecrets.aws.region | quote }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ include "popper.serviceAccountName" . }}
    {{- else }}
    vault:
      server: {{ .Values.externalSecrets.vault.server | quote }}
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: {{ .Values.externalSecrets.vault.role | quote }}
          serviceAccountRef:
            name: {{ include "popper.serviceAccountName" . }}
    {{- end }}
{{- end }}
