{{- if and .Values.externalSecrets.enabled .Values.externalSecrets.secretStore.create -}}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecrets.secretStoreRef.name }}
  labels:
    {{- include "popper.labels" . | nindent 4 }}
spec:
  provider:
    vault:
      server: {{ .Values.externalSecrets.vault.server | quote }}
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: {{ .Values.externalSecrets.vault.role | quote }}
          serviceAccountRef:
            name: {{ include "popper.serviceAccountName" . }}
{{- end }}
