# Development overrides
replicaCount: 1

autoscaling:
  enabled: false

podDisruptionBudget:
  enabled: false

queueWorker:
  replicaCount: 1
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 250m
      memory: 256Mi

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 250m
    memory: 256Mi

config:
  LOG_LEVEL: "debug"
  NODE_ENV: "development"

externalSecrets:
  enabled: false
