# Staging overrides
replicaCount: 2

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilization: 80
  targetMemoryUtilization: 85
  scaleDownStabilization: 180

podDisruptionBudget:
  enabled: true
  minAvailable: 1

queueWorker:
  replicaCount: 1

ingress:
  enabled: true
  hosts:
    - host: popper-api.staging.regain.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: popper-api-staging-tls
      hosts:
        - popper-api.staging.regain.com

externalSecrets:
  enabled: true
  environment: "staging"
